[package]
name = "json-web-token"
description = "A ser(de) for JWTs, JWS and the basic structs for representing them."
edition = "2024"
homepage = "https://github.com/Ameelio/json-web-token/"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ameelio/json-web-token/"
version = "0.2.0"

[features]
debug = [
  "dep:tracing"
]

[dependencies]
thiserror = "2.0.18"

base64ct = { version = "1.8.0", features = ["std"] }
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
tracing = { version = "0.1.44", optional = true }

[dev-dependencies]
hmac = "0.12.1"
serde_test = "1.0.177"
sha2 = "0.10.9"

